import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7F8FA',
  },
  content: {
    padding: 16,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#0B1220',
    marginBottom: 12,
  },
  ongCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 16,
  },
  ongName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#0B1220',
    marginBottom: 8,
  },
  ongInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  ongInfoText: {
    fontSize: 14,
    color: '#6B7280',
    marginLeft: 8,
  },
  selectOngButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 80,
  },
  selectOngButtonText: {
    fontSize: 16,
    color: '#22C55E',
    fontWeight: '500',
    marginTop: 8,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    fontSize: 16,
    color: '#0B1220',
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#0B1220',
    marginBottom: 8,
  },
  valorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  valorSymbol: {
    fontSize: 18,
    fontWeight: '600',
    color: '#0B1220',
    marginRight: 8,
  },
  valorInput: {
    flex: 1,
    fontSize: 18,
    fontWeight: '600',
    color: '#0B1220',
  },
  metodoPagamentoContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  metodoButton: {
    flex: 1,
    minWidth: '45%',
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E5E7EB',
  },
  metodoButtonSelected: {
    borderColor: '#22C55E',
    backgroundColor: '#F0FDF4',
  },
  metodoButtonText: {
    fontSize: 14,
    color: '#0B1220',
    fontWeight: '500',
    marginTop: 8,
  },
  observacaoInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    fontSize: 14,
    color: '#0B1220',
    minHeight: 100,
    textAlignVertical: 'top',
  },
  button: {
    backgroundColor: '#22C55E',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 8,
  },
  buttonDisabled: {
    backgroundColor: '#E5E7EB',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#FFFFFF',
  },
});

